### ISSUE TITLE
Overlapping vertical conjuncts in Nandinagari

### ISSUE THREAD

**Issue by dscorbett** [notofonts/nandinagari#3]
### Font
NotoSansNandinagari-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/9b479a1e7c843da5ea247530a8578f288b49f870/unhinted/otf/NotoSansNandinagari/NotoSansNandinagari-Regular.otf
Date: 2022-03-05

### Font version
Version 1.000

### Issue
Many vertical conjuncts beginning with <i>ka</i>, <i>ca</i>, <i>ta</i>, <i>na</i>, <i>ba</i>, and <i>la</i> have leftwards headstrokes that are too long and overlap the preceding glyph.

### Character data
𑦪𑦮𑧠𑦮
U+119AA NANDINAGARI LETTER E
U+119AE NANDINAGARI LETTER KA
U+119E0 NANDINAGARI SIGN VIRAMA
U+119AE NANDINAGARI LETTER KA

### Screenshot
![𑦪𑦮𑧠𑦮](https://user-images.githubusercontent.com/1124347/156905629-97ed453e-de92-4527-b100-0197d2353c18.png)

**Comment by simoncozens** [comment]
Okay. I see what's happening here. The headline is produced in Glyphs using the "Smart Components" feature, which we currently don't support, so instead of being scaled to fit, it is being added as a component at 100% of its design size.

The cool way to fix this would be to support smart components in glyphsLib.

**Comment by simoncozens** [comment]
I have implemented smart components in Glyphs, so a rebuild will fix this.
